REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'DBREMOTEUSER'@'localhost' ;
GRANT EXECUTE ON PROCEDURE `fbwu`.`CreateApiary` to 'DBREMOTEUSER'@'localhost' ;
GRANT EXECUTE ON PROCEDURE `fbwu`.`CreateHarvest` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`CreateHive` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`CreateInspection` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`CreateUser` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`DeleteApiaryByID` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`DeleteHarvestByID` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`DeleteHiveByID` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`DeleteInspectionByID` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`DeleteUserByID` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`AssignApiary` to 'DBREMOTEUSER'@'localhost';
GRANT EXECUTE ON PROCEDURE `fbwu`.`AssignHive` to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON ApiaryView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON BeeToolsCondDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON ColStrengthDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON DeasPestValDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON HarvestView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON HiveCondDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON HiveStateDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON HiveTemperDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON HiveTypeDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON HiveView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON InspectionView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON OwnedApiaryView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON StoresDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON SunExpDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON UserRoleDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON UserView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON WeatherCondDict to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON OwnedHivesView to 'DBREMOTEUSER'@'localhost';
GRANT SELECT ON MapView to 'DBREMOTEUSER'@'localhost';